### ISSUE TITLE
Hope to post issues in here instead of main branch.

### ISSUE THREAD

**Issue by usbcnc** [usbcnc/grbl#1]
If you have any issues regarding this port, please post here instead go to main branch's ARM discussing. 

Also attached prebuild in here. You can use serial port to load to your module.
[stm32grbl.zip](https://github.com/usbcnc/grbl/files/685443/stm32grbl.zip)

**Comment by ewidance** [comment]
I don't know if this binay have been built with -DLEDBLINK -DUSEUSB, but i can't enumerate device while connected to USB on OSX with lsusb. Additionnaly, led is always ON....

**Comment by usbcnc** [comment]
Can you try on Windows first? I have not tried this on OSX,

**Comment by ewidance** [comment]
I just tried the prebuilt on Windows, and it'd not enumerated. I'm using a 'Blue Pill', STM32F103C8T6. Code have been flashed on Windows with genuine  ST-Link utility.

**Comment by usbcnc** [comment]
Which driver do you use? Microsoft or ST's VCP?

**Comment by usbcnc** [comment]
@ewidance Do you mind me take a look of your setup via teamviewer?  I am interested to see others using this build.

**Comment by ewidance** [comment]
Ok i found it. I was using a 'bluepill', with the clock jumper removed. Board was running on internal rc osc @wrong frequency. After putting back the jumper port is properly enumarated under windows 10 (VM) & OSX (Sierra). Thanks a lot.

**Comment by usbcnc** [comment]
Great!.

**Comment by usbcnc** [comment]
I can only see two jumpers and both are for the boot select.

**Comment by ewidance** [comment]
It not exactly a blue pill.  It's a STM32F103C8T6 STM32 Minimum System Development Board. The clock jumper is P2.

![image](https://cloud.githubusercontent.com/assets/2135006/23234433/5e0b77c2-f952-11e6-8a66-4c859e92b8d0.png)
