### ISSUE TITLE
Coolant Flood Bit on GPIOB pin 2

### ISSUE THREAD

**Issue by Elvenblood** [usbcnc/grbl#12]
Maybe not such a big deal, but using pin 2 for the coolant bit might not be so good since it's also the boot pin. Perhaps move it?

I'm very new to this architecture so i'm sorry if I'm mistaken.

**Comment by robomechs** [comment]
Yes. I've also remapped it in my project.
But it's not a problem. You can easy remappe it in cpu_map.h
