### ISSUE TITLE
Arduino IDE environment

### ISSUE THREAD

**Issue by mkeyno** [usbcnc/grbl#14]
thanks @usbcnc for porting to such platform , however I've tried to change it and uploaded to my board regards to instructions , I think it little be handy , do you have plan to port it base on [Roger Clarck repo](https://github.com/rogerclarkmelbourne/Arduino_STM32),  its very stable now ?

**Comment by usbcnc** [comment]
No, I am not Arduino guy myself.

**Comment by mkeyno** [comment]
@usbcnc  why cpu_map.h is empty? have anybody use your lib for CNC laser?

**Comment by yaroslavVl** [comment]
What do you mean "empty"?

**Comment by yaroslavVl** [comment]
What do you mean "empty"?
https://github.com/usbcnc/grbl/blob/edge/grbl/cpu_map.h

**Comment by usbcnc** [comment]
I do not consider this file is empty. 
I a out of town. I have ordered a laser module a while ago but have not arrived yet. I will test laser mode after I got it.

**Comment by mkeyno** [comment]
I couldn't find couple of file like cpu_map.h  in coocox project tab or any other tab!
@usbcnc  when I install ST-link adapter , it just make installation in hardware usb category and not port category (STMicroelectronics STLink dongle) and not let the flash begin
```
Error: Connect failed, check config and cable connection
```

**Comment by usbcnc** [comment]
I see what you mean about cpu_map.h. In the project if the .h file is specified you can easily open to edit. However it will not affect the compilation. You can still open the file from file menu.
STlink is not in port category. (like COM). You should better copy and paste your screen of device manager to see what is going on.

**Comment by mkeyno** [comment]
please check the image 
![new bitmap image](https://user-images.githubusercontent.com/6232001/27140017-be5d7b18-5139-11e7-84f0-6f0c8b47281b.jpg)

**Comment by usbcnc** [comment]
I have checked in project with cpu_map.h

**Comment by mkeyno** [comment]
@usbcnc  can I have you advise why STLink dongle not appear in port category ? also as previous discussion I was hopping I have your STM pinout for CNC laser 
thanks

**Comment by usbcnc** [comment]
STLink is not a comport. You see this under Universal Serial Bus devices.
I will update the laser stuff once I have a changce to play it myself.

**Comment by mkeyno** [comment]
I know that but the coocox seek the com port to upload the hex or I definitely miss somethings ?

**Comment by usbcnc** [comment]
You need to setup properly on coocox. Setup teamviewer and I can help you out.
You can also use ST tool to program the target.

**Comment by misan** [comment]
CoFlash tool worked for me too. http://www.coocox.org/software/CoFlash.php
