### ISSUE TITLE
PB3, PB4 and PA15 pins doesn't work (SOLVED)

### ISSUE THREAD

**Issue by robomechs** [usbcnc/grbl#15]
To enable PB3, PB4 and PA15 pins you have to disable JTAG:
GPIO_PinRemapConfig(GPIO_Remap_SWJ_JTAGDisable, ENABLE);

**Comment by usbcnc** [comment]
I checked in the code in main.c

**Comment by alk1913** [comment]
hello,i am very excited whit this for of grbl.i am a user of grbl  in arduino,bat my experience whit this board(STM32f103 is really good ,i get the spindle PWM wor nice,and the coolant flo0d (PB3),isn t work,i remap tp PA9 and on this moment i not have troubles!!!THANKS ALL

**Comment by SailWithChips** [comment]
Hello, thanks a lot for your work.
I've done same like **alk1913** and working succesful but I'm not able to have PA15 as probe input working as expected:
I added on main.c (line 92 - 95):
`#if defined (STM32F103C8)
    GPIO_PinRemapConfig(GPIO_Remap_SWJ_Disable, ENABLE);`

Also tested with (and not succesful):
 `GPIO_PinRemapConfig(GPIO_Remap_SWJ_JTAGDisable, ENABLE);`


I have allways fixed 3.17 volts on PA15... could anyone help me with this?.

Thanks a lot in advanced,

**Comment by SailWithChips** [comment]
Hello it seems to work propperly now. I did what mention on Probe pin invert FIX #32, adding this in probe.c:
`uint16_t probe_invert_mask;`
