### ISSUE TITLE
What about a short instruction?

### ISSUE THREAD

**Issue by robomechs** [usbcnc/grbl#17]
For instance:
- by default all input pins with pull-up,
- you can remap CTRL_ pins only within pb5-pb9 (or pa5-pa9),
- you can remap limit pins only within pb10-pb15 (or pa10-pa15),
- e.t.c

**Comment by robomechs** [comment]
- Available PA0-PA10, PB0-PB2, PB5-PB15.
- PA11-PA14 - reserved (USB, SWD)
- PA15, PB3, PB4 - not avaliable yet (because of JTAG), but may be later.

**Comment by usbcnc** [comment]
Use GPIO_PinRemapConfig(GPIO_Remap_SWJ_Disable, ENABLE); can free up PB3,PB4.PA15.PA11
