### ISSUE TITLE
pinout for cnc laser

### ISSUE THREAD

**Issue by mkeyno** [usbcnc/grbl#18]
sorry to open ticket for my question but actually I've tired to build cnc laser controller with Arduino compatible  STF103CT6 board , however I've bit lost to assign the pins to the boards ,little hint really appreciated

**Comment by mkeyno** [comment]
@usbcnc  I really appreciated for you hint

**Comment by usbcnc** [comment]
I will soon get a laser module myself. I will see how to put it together.

**Comment by mkeyno** [comment]
@usbcnc can you  direct me to the file with pinout  definition

**Comment by usbcnc** [comment]
The control pin for laser is pin A8.  So far I am using $32=0.

**Comment by usbcnc** [comment]
Check video. https://www.youtube.com/watch?v=CQwOXgtFz2o&t=6s

**Comment by mkeyno** [comment]
thanks for video , just for confirmation please check following image if it's correct
![stm32f103c8t6 -laser pin](https://user-images.githubusercontent.com/6232001/27992797-75338118-64b1-11e7-859a-00e46ae14e2a.jpg)

**Comment by usbcnc** [comment]
@mkeyno PA9 and PA10 are not used for serial port. I use USB virtual COM port. So USB is not only power but also the main communication port to PC. Initially I found a need to use serial port for debugging. The SWD debugging was not working when USB is enabled. I found SWD debugging not reliable and use Windows is what I do most of the time to debug. 
Your spindle direction and spindle enable is different than mone, Mine was set to PB13 and PB14. Again you can find all the definition in cpu_map.h other than the PA9 and PA10 for serial port which is no longer needed.

**Comment by mkeyno** [comment]
thanks @usbcnc  actually I found this configuration in cpu_map.h but not sure I referring to correct source, however I use bluetooth or wifi as serial bridge for every cnc I made so USB link is not helpful , can you give me advise what pins are better to use for wireless connection
BR
