### ISSUE TITLE
chip name problem

### ISSUE THREAD

**Issue by robomechs** [usbcnc/grbl#2]
did not find stm32f103c8 chip in coide 2.0.6 (Build id: 20170117-2.0.6). Which version do you use? I suppose it have to be stm32f103c8t6 to work well.
![2017-02-16_11-26-07](https://cloud.githubusercontent.com/assets/8062959/23013249/e524915c-f43a-11e6-8fec-d3d64735af5e.png)
![2017-02-16_11-26-22](https://cloud.githubusercontent.com/assets/8062959/23013254/e82a9a7c-f43a-11e6-91f4-85a5464afbaf.png)
my other projects in stm32f103c8t6 (the board is the same as yours) are opened and work.

**Comment by robomechs** [comment]
Ok, I changed it only in stm32grbl11d.coproj, and project is opened

**Comment by SailWithChips** [comment]
Hello, same problem like you. Where do you changed it?. Plase could you attach some photo or something to know what to do. Thanks in advanced,
