### ISSUE TITLE
Inital Active State: Alarm

### ISSUE THREAD

**Issue by roofg** [usbcnc/grbl#22]
Props on the good work for this Project!

I followed your instructions on the how to build and run GRBL video. I built the project in coocox. Set the Bootpin 0 to High and flashed the created .hex file with ST Flash Loader Demonstrator via serial connection. 

I connected pc to board usb (shows up as STM Serial Com12) and used Universal Gcode Sender to connect to GRBL ( Com12, Baud11520, Firmware GRBL). This is the output i get from consol:

**** Connected to COM12 @ 115200 baud ****

Grbl 1.1f ['$' for help]
>>> $$
>>> $G
$0=10
$1=0
$2=7
$3=7
$4=0
$5=0
$6=0
$10=1
$11=0.010
$12=0.002
$13=0
$20=0
$21=0
$22=1
$23=3
$24=25.000
$25=500.000
$26=250
$27=1.500
$30=100
$31=0
$32=0
$100=400.000
$101=400.000
$102=400.000
$110=600.000
$111=600.000
$112=600.000
$120=45.000
$121=45.000
$122=45.000
$130=200.000
$131=300.000
$132=50.000
ok
[verbose]GrblFeedbackMessage{message='[GC:G0 G54 G17 G21 G90 G94 M5 M M9 T0 F0 S0]', distanceMode='G90', units='G21'}
[GC:G0 G54 G17 G21 G90 G94 M5 M M9 T0 F0 S0]
ok
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P|WCO:0.000,0.000,0.000>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P|Ov:100,100,100|A:S>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P|WCO:0.000,0.000,0.000>
[verbose]<Alarm|MPos:0.000,0.000,0.000|FS:0,0|Pn:P|Ov:100,100,100|A:S>

--------------------------------------------------------------------------------

From there on the output just loops and the Machine status from UGCS is Active State: Alarm.

My question is, did i do something wrong and how can i resolve it?Or is this a code/port based problem?

Thanks for your work on the project :) cheers

**Comment by usbcnc** [comment]
You enabled homing and default in Alarm state.
Either disable homing or do a proper homing.
$X also kills the alarm. This is not a bug it is by design.
