### ISSUE TITLE
coolant on PB3 doesn´t work

### ISSUE THREAD

**Issue by alk1913** [usbcnc/grbl#23]
i try to connect a relay to PB3 fora coolant fan ,but thisnot work.if i change thr pin for coolant from PB3 to PA9 this work perfectly.
why happen that?
thank you for your work!!
and if you can help me with this!!!

**Comment by usbcnc** [comment]
PB3 default function is mapped to JTDO / TRACESWO. Need to disable it if PB3 is used.

**Comment by usbcnc** [comment]
Change 
RCC_APB2PeriphClockCmd(RCC_COOLANT_FLOOD_PORT, ENABLE);
to 
RCC_APB2PeriphClockCmd(RCC_COOLANT_FLOOD_PORT| RCC_APB2Periph_AFIO , ENABLE);
GPIO_PinRemapConfig(GPIO_Remap_SWJ_JTAGDisable , ENABLE);

PB3 then can be used.
