### ISSUE TITLE
Missing STM32F103C8T6.ld

### ISSUE THREAD

**Issue by siy** [usbcnc/grbl#26]
I've tried to build code from repository (using make), but build process fails because of missing file. Where I can find it? And, perhaps, it worth to include it in order to enable building without IDE. This is especially important taking into account that CooCox is not working under OS'es other than Windows.

**Comment by usbcnc** [comment]
Try to google it. Have not played with make file for a while.

**Comment by ChristianRinn** [comment]
I've opened a pull request which fixes the missing linker script and another bug in the Makefile: https://github.com/usbcnc/grbl/pull/34
