### ISSUE TITLE
Porting to v1.1f ?

### ISSUE THREAD

**Issue by suprimex** [usbcnc/grbl#28]
is there any chances to port it to GRBL v1.1f  ?

**Comment by robomechs** [comment]
what's the difference?

**Comment by radiolee** [comment]
It's already 1.1f
![Uploading 1.png…]()

**Comment by radiolee** [comment]
It's already 1.1f in Aug 1
![1](https://user-images.githubusercontent.com/35003866/34510245-2f2a676e-f08d-11e7-9690-d981d97ae89b.png)

**Comment by usbcnc** [comment]
It is already latest.
