### ISSUE TITLE
What is the step rate of grbl STM32?

### ISSUE THREAD

**Issue by radiolee** [usbcnc/grbl#33]
We know grbl@arduino, pulse feq is about 30khz,  what now upgrade to 32bit@72MHz?

**Comment by usbcnc** [comment]
I tried to 180KHz without issue.

**Comment by radiolee** [comment]
Thanks, this is great.

**Comment by usbcnc** [comment]
If you need higher rate, you can.
1 Over clock the CPU. Then you might not be able to use USB but you can use serial port.
2. Use STM32F4 which runs at 168MHZ. So I assume the step rate can be easily go to 500KHz

**Comment by radiolee** [comment]
Thanks for reply.  About 200kHz is suitable, lots of stepper driver working around this rate. BTW, is serial port working with USB enable? or must disable USB then serial is working? 
I just want connect a ESP8266 websocket module, is usb and serial working together or how to switch it quickly?

**Comment by radiolee** [comment]
@usbcnc about 200kHz step rate is great for many stepper driver.
