### ISSUE TITLE
How to toggle USB VCP and serialport by an IO pin?

### ISSUE THREAD

**Issue by radiolee** [usbcnc/grbl#35]
USEUSB was defined symbols in configuration, there is still free IO pins left.
It's because I want try ESP8266 websocket connection and keep USB VCP support, toggle it by a jumpper or a switch on the panel. @usbcnc could you support it as enhancement? or the both port working together maybe a good idea?

**Comment by usbcnc** [comment]
What is the use of ESP8266 on Grbl? I do not have tested this module.

**Comment by misan** [comment]
ESP8266 can be used as a serial-to-wifi module using ESP-LINK software for example.
https://github.com/jeelabs/esp-link

This enables wireless operation of grbl through a TCP connection.

**Comment by radiolee** [comment]
Yes, the ESP module is a Websocket<>Serial Bridge, less  than $2, run at 160MHz, it's create connection via wifi for grbl. 
https://github.com/LaserWeb/LaserWeb3-ESP8266

**Comment by radiolee** [comment]
I am close this because it is easy to use serial, just re-flash stm.
