### ISSUE TITLE
Question: does it have better performace then the avr version? 

### ISSUE THREAD

**Issue by aster94** [usbcnc/grbl#37]
Hello,

I have a few stm32f1 around but i am in doubt if them would perform really better then the avr

From your account i see that you made both the mega version then this. Which is your experience about? The more powerful stm32 outperform the tiny 8bit? Which would you suggest for a new design?

**Comment by usbcnc** [comment]
Yes it is far better than the AVR. The step rate can go up to 180Khz while AVR can only do 33Khz.
