### ISSUE TITLE
G-Code G4 not working correctly

### ISSUE THREAD

**Issue by lakeroe** [usbcnc/grbl#38]
In my application the G-Code "G4 P3" did not work correctly.
I think the problem is caused by the _delay_ms function in main.c.
If I change line 196 from
SysTick->LOAD = (u32)72000000 / 8000;                     // Loading time

to
SysTick->LOAD = (u32)72000000 / 8000 * x;                     // Loading time

everything works fine.

Best regards,
lakeroe

**Comment by usbcnc** [comment]
Thanks,
