### ISSUE TITLE
PINOUT

### ISSUE THREAD

**Issue by creisey** [usbcnc/grbl#42]
Hi there

first thanks for your work to port GRBL to the STM32!

i've managed to Flash mine and run it.

the only Thing i've not found out yet is the pinout:

from this Picture:

http://wiki.stm32duino.com/images/a/ae/Bluepillpinout.gif

i've seen the labled Pins in relationship to arduino

but if i connect for instance A2 as X-step and A5 as X-dir the stepper doesnt move... Any idea?

**Comment by martin2250** [comment]
Hi,
you can find the pinout in [cpu_map.h](https://github.com/usbcnc/grbl/blob/edge/grbl/cpu_map.h)

**Comment by creisey** [comment]
![pinout](https://user-images.githubusercontent.com/19647655/39619939-d2f3de9c-4f89-11e8-9fe0-19bd6d88cbea.jpg)

well i created a document with the PINOUT for the STM32 -GRBL Layout.

should it be like that?

**Comment by ChristianRinn** [comment]
You can have a look here:
https://github.com/usbcnc/grbl/issues/18#issuecomment-313909977

**Comment by creisey** [comment]
![pinout](https://user-images.githubusercontent.com/19647655/39626330-b8cdf652-4fa1-11e8-9596-38fedb711441.jpg)
well i corrected mine, i still have no clue how the pin's are assigned

in the cpu_map.h i read for instance 
 #define X_STEP_BIT      2  // Uno Digital Pin 2 that would mean for me A2 = X-Step

however i with the hint for the laser it worked

**Comment by ChristianRinn** [comment]
Have a look at the section beginning with #ifdef CPU_MAP_STM32F103
e.g.
```
  // Define step pulse output pins. NOTE: All step bit pins must be on the same port.
#define STEP_PORT       GPIOA
#define RCC_STEP_PORT   RCC_APB2Periph_GPIOA
#define X_STEP_BIT      0  
#define Y_STEP_BIT      1  
#define Z_STEP_BIT      2
#define STEP_MASK       ((1<<X_STEP_BIT)|(1<<Y_STEP_BIT)|(1<<Z_STEP_BIT)) // All step bits
```

So you have all step pins at GPIOA, with x-step at PA_0, y-step at PA_1 and z-step at PA_2.

**Comment by creisey** [comment]
you're absolutely right, i haven't gone that far.
