### ISSUE TITLE
USB problem on Maple Mini

### ISSUE THREAD

**Issue by ewidance** [usbcnc/grbl#5]
On Maple mini board, PB9 is used to reset usb port throught a stage with 2 transistors. Unitialised state acts as an output to '1' and drive those transistors, resetting USB port. 

Since PB9 is unused on current pin mapping, it coulb be initialsed ans output to 0, and leaved as is...
I've tested in main loop. Maple mini is properly enumarated on USB now. 
```
....
#else
int main(void)
#endif
{#if defined (STM32F103C8)
	GPIO_InitTypeDef GPIO_InitStructure;
#ifdef LEDBLINK
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOC, ENABLE);
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_2MHz;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_13;
	GPIO_Init(GPIOC, &GPIO_InitStructure);     
#endif

	// init PB9 as out port for maple mini
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB, ENABLE);
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_9;
	GPIO_Init(COOLANT_FLOOD_PORT, &GPIO_InitStructure);
	GPIO_WriteBit(GPIOB, GPIO_Pin_9, Bit_RESET);
....
```

**Comment by usbcnc** [comment]
If you want to debug on target you need to disable USB and PA9 and PA10 will be the serial port data. However I found the Win32 debug is enough.
