### ISSUE TITLE
4th and 5th axis

### ISSUE THREAD

**Issue by ArsBinarii** [usbcnc/grbl#58]
Hey guys, might be a stupid question but I can't find the branch or any configuration for the 4th and 5th axis in 7e3308b. Where is the code for the 4th and 5th axis?

Thanks

**Comment by robomechs** [comment]
There are no branches for the 4th and 5th axis.
Unfortunately @usbcnc has no activities since January 2017.
See https://github.com/usbcnc/grbl/issues/51#issuecomment-408638999 to get version for 4/5/6 axis.
