### ISSUE TITLE
LedBlink does not work

### ISSUE THREAD

**Issue by ewidance** [usbcnc/grbl#9]
LedBlink function in main() doens not seems to be called anywhere, so led stays off...

**Comment by usbcnc** [comment]
Did you compile yourself? It is only blinked for each G code executed.

**Comment by ewidance** [comment]
Yes i did. Where is it activated?

**Comment by usbcnc** [comment]
@ewidance You are right, it is not enabled. I forgot to port over from 1.1d code.
I will fix it in next merge of 1.1f.
